name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main  # デプロイするブランチ

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Add known_hosts
      run: |
        echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh bitcat@www.iput-kernel.com "cd /opt/iput-kernel/foundation-frontend &&git stash &&git pull origin main && yarn && yarn build"
